# Sandbox to try random things quickly

In [1]:
import numpy as np

In [8]:
a = np.ones((5,5))
a[1,:] = -1
i = range(5)
a[i,i] = np.maximum(a[i,i], 0)
a

array([[ 1.,  1.,  1.,  1.,  1.],
       [-1.,  0., -1., -1., -1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [4]:
a = np.array([1,2,3])
print(a[:, np.newaxis])
print(np.expand_dims(a, axis=1))

[[1]
 [2]
 [3]]
[[1]
 [2]
 [3]]


In [5]:
a = tuple(zip([1,2,3], (4,5,6)))
a

((1, 4), (2, 5), (3, 6))

In [2]:
tuple(zip(*a))

((1, 2, 3), (4, 5, 6))

In [3]:
g = {1:[2,3], 2:[0,1]}
x,y = zip(*g.items())
max(list(x) + [i for a in y for i in a])

3